spring:
  # Tells Spring Boot to extract the real client IP and protocol from Nginx's X-Forwarded-* headers
  forward-hdr-strategy: framework

  application:
    name: QuoraApp

  # ---- MONGO-DB ------
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true

    #----- REDIS -------
    redis:
      host: localhost
      port: 6379

  jackson:
    serialization:
      write-dates-as-timestamps: false


  #------ KAFKA --------
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: quora-app
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false



app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000           # 24 hrs (down from 24 hours)
  refresh-token:
    expiration-ms: 604800000        # 7 days

  
  # ------ OLlAMA ---------
  ollama:
    base-url: http://localhost:11434
    model: nomic-embed-text


  # ----------- CLOUDINARY -----------
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}


# -- SWAGGER

springdoc:
  api-docs:
    # Allows turning off raw JSON spec endpoint in certain environments if needed
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    # Explicitly sets the browser dashboard access path
    path: /swagger-ui.html
    supported-submit-methods: ["get", "post", "put", "delete", "patch"]
    tags-sorter: alpha
    operations-sorter: method
  packages-to-scan: com.quora