spring:
  application:
    name: QuoraApp

  # ---- MONGO-DB ------
  data:
    mongodb:
      uri: mongodb://localhost:27017/quora
      auto-index-creation: true

    #----- REDIS -------
    redis:
      host: localhost
      port: 6379


  #------ KAFKA --------
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: quora-app
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false


# ----- JWT -------
app:
  jwt:
    secret: 7d4f9c2a8e5b1f6d3a9c7e2b8f4d1a6c9e3f7b2a5d8e1c4f9a6b3d7e2c8f5a1
    expiration-ms: 86400000  #24 hr